<a href="https://colab.research.google.com/github/InTaewoo/study/blob/main/python/%ED%8C%8C%EC%9D%B4%EC%8D%AC_class%EC%97%B0%EC%8A%B5ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
[x**2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
who = ['소방서','경찰서']
number = [119,112]
for w,n in zip(who,number) :
  print(f'{w}는 {n} 입니다')

소방서는 119 입니다
경찰서는 112 입니다


In [ ]:
for i,w in enumerate(who) :
  print(f'{i}번째 주소는 {w} 입니다')

0번째 주소는 소방서 입니다
1번째 주소는 경찰서 입니다


In [ ]:
sum = 0
for i in range(1,11):
  sum += 1**2

print(sum)

10


In [ ]:
import numpy as np

# 4x3 matrix
np.arange(12).reshape(3,4)

a = np.arange(12)
a.shape = (4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
temp = []
a_lst = []
for i in range(12):
  temp.append(i)
  if i % 3 == 2:
    a_lst.append(temp)
    temp = []
print(a_lst)

[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]]


In [ ]:
a = np.array(a_lst)
a.shape

(4, 3)

In [ ]:
import random

np.random.rand(10)
np.random.rand(4,3)
np.random.randn(4)


array([-1.03437201,  0.20018784,  0.52018992, -0.18804542])

In [ ]:
# OTP 개발
''.join(np.random.choice(list('0123456789'),6))

'109896'

In [ ]:
''.join(np.random.choice(list('abcdefghijklmnopqrstuvwxyz0123456789'),6)).upper()

'SJFSC9'

In [ ]:
a = np.arange(12).reshape(4,3)
b = np.array(range(12,0,-1)).reshape(4,3)
a-b

array([[-12, -10,  -8],
       [ -6,  -4,  -2],
       [  0,   2,   4],
       [  6,   8,  10]])

In [ ]:
result = 0
def adder(num):
  global result
  result += num
  return result

print(adder(10))
print(adder(11))

10
21


In [ ]:
class Calculator:
  def __init__(self):
    self.result = 0

  def adder(self,num):
    self.result += num
    return self.result

cal1 = Calculator()
cal2 = Calculator()
print(cal1.adder(3))
print(cal1.adder(4))
print(cal2.adder(3))
print(cal2.adder(7))


3
7
3
10


In [ ]:
class Service :
  secret = '영구는 배꼽이 두개다'
  def sum(self,a,b):
    result = a+b
    print(f'{a}+{b}={result}입니다')

pey = Service()
pey.sum(142,1)

142+1=143입니다


In [ ]:
class Service:
  secrete = '영구는 배꼽이 두개'

  def set_name(self,name):
    self.name = name

  def sum(self,a,b):
    result = a+b
    print(f'{self.name}님 {a}+{b}={result}입니다')

 



In [ ]:
a = Service()
a.set_name('홍길동')


In [ ]:
a.sum(1,1)

홍길동님 1+1=2입니다
