In [1]:
import numpy as np

In [3]:
data=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a.dtype

dtype('int64')

In [5]:
type(a)

numpy.ndarray

In [7]:
a=a.astype(np.float32) #a= a.astype('float32')
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [9]:
a[0][1]

2.0

In [10]:
a[0]

array([1., 2., 3.], dtype=float32)

In [11]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(1,13).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [16]:
np.nan* 10

nan

In [17]:
a[0][1]

2.0

In [18]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [20]:
a= np.linspace(1,10,10) 
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
data=np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
data+data #원소들끼리 계산
data-data
data*data
data/data


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
#차원
#0차원 : 스칼라
a=np.array(1)
a

array(1)

In [28]:
a.shape

()

In [29]:
a.ndim #몇차원이니?

0

In [32]:
#1차원 : 벡터
a=np.array([1,2,3,4,5])
a.shape
a.ndim

1

In [35]:
#2차원 : 행렬
a=np.array([[1,2,3],[4,5,6]]) #괄호가 2개라 2차원
a.shape
a.ndim

2

In [38]:
#3차원 : 3차원 이상의 다차원 행렬 Tensor
a= np.array([[[1,2],[3,4],[5,6]]])
a
a.shape
a.ndim

3

In [40]:
#matrix의 유형
a=np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [43]:
b=np.ones(12)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
c=np.zeros(12).reshape(2,3,2)
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [45]:
d=np.eye(3) #단위행렬
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
f=np.empty([2.3])
f

TypeError: ignored

In [50]:
g=np.full((3,4),1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [52]:
#집계함수
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
a[0][0]=100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [55]:
a[0,1]=1000
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [57]:
np.mean(a) #평균

114.4

In [58]:
np.median(a) #중앙값

6.5

In [59]:
np.std(a) #표준편차

296.5485457728633

In [62]:
np.sum(a,axis=0) #어디서 더할지 축설정

array([ 105, 1006,    9,   11,   13])