<a href="https://colab.research.google.com/github/InTaewoo/study/blob/main/numpy/%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%B2%A0%EC%A0%80%EC%9E%85%EB%AC%B8_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

data1= [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [6]:
data2 = [0.1,5,4,12,0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [9]:
a1.dtype

a2.dtype


dtype('float64')

In [10]:
a1.dtype

dtype('int64')

In [13]:
s = np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b1=np.arange(12).reshape(3,4)

In [19]:
b1.shape

(3, 4)

In [20]:
b2 = np.arange(5)
b2.shape

(5,)

In [21]:
np.linspace(1,10,20) # 1부터 10까지의 20개의 배열

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [22]:
np.linspace(0,np.pi,20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
a=np.array(['1.5','23','2,5','1662'])
a[:2]

array(['1.5', '23'], dtype='<U4')

In [35]:
np.random.rand(2,3)

array([[0.3166715 , 0.39564447, 0.54449703],
       [0.10858359, 0.59959578, 0.22989736]])

In [39]:
np.random.rand(2,3,4)

array([[[0.53980068, 0.46015813, 0.74951435, 0.60154635],
        [0.32810156, 0.90643774, 0.91848206, 0.08774821],
        [0.17952244, 0.57165066, 0.40094286, 0.67150987]],

       [[0.7477909 , 0.17578684, 0.61616773, 0.64502276],
        [0.32483414, 0.47769749, 0.58264759, 0.118009  ],
        [0.62138578, 0.6256301 , 0.44216231, 0.05680649]]])

In [40]:
np.random.randint(10,size=(3,4))

array([[2, 7, 6, 6],
       [1, 6, 6, 4],
       [5, 1, 7, 2]])

In [43]:
np.random.rand(2,4)

array([[0.38136579, 0.5212382 , 0.62967623, 0.17287769],
       [0.87938964, 0.86743427, 0.71399566, 0.66669835]])

In [44]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])
arr1+arr2

array([11, 22, 33, 44])

In [45]:
arr1-arr2

array([ 9, 18, 27, 36])

In [46]:
arr2*2

array([2, 4, 6, 8])

In [47]:
arr2**2

array([ 10,  40,  90, 160])

In [49]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [51]:
[arr3.sum(),arr3.mean()]

[10, 2.0]

In [54]:
[arr3.std(),arr3.var()]

[1.4142135623730951, 2.0]

In [55]:
arr4 = np.arange(1,5) #누적합

In [56]:
arr4.cumsum()

array([ 1,  3,  6, 10])

In [57]:
arr4.cumprod() # 누적곱

array([ 1,  2,  6, 24])

In [60]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [62]:
B = np.array([3,2,5,2]).reshape(2,2)
B

array([[3, 2],
       [5, 2]])

In [63]:
A.dot(B) # 행렬의곱

array([[ 5,  2],
       [21, 10]])

In [64]:
a1 =np.array([10,20,30,40,50,0])
a1

array([10, 20, 30, 40, 50,  0])

In [67]:
a1[0]

10

In [71]:
a1[5]=100
a1

array([ 10,  20,  30,  40,  50, 100])

In [77]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [78]:
a2[2,2]

90

In [79]:
a2[1,2]=30
a2

array([[10, 20, 30],
       [40, 50, 30],
       [70, 80, 90]])

In [80]:
a=np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [82]:
a[ :3]

array([1, 2, 3])